services:
  # Backend API Service
  - type: web
    name: mini-crm-backend
    runtime: node
    plan: starter
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    healthCheckPath: /auth/healthz
    autoDeploy: true
    envVars:
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CALLBACK_URL
        value: https://mini-crm-backend.onrender.com/auth/google/callback
      - key: FRONTEND_URL
        value: https://mini-crm-frontend.onrender.com
      - key: CORS_ORIGIN
        value: https://mini-crm-frontend.onrender.com

  # Frontend Service
  - type: web
    name: mini-crm-frontend
    runtime: node
    plan: starter
    buildCommand: cd crm-frontend && npm install && npm run build
    startCommand: cd crm-frontend && npx serve -s dist
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://mini-crm-backend.onrender.com 